### ISSUE TITLE
Backend - code refac

### ISSUE THREAD

**Issue by kpiechura** [kpiechura/speechy-recon-app#14]
The whole `main.py` code should be refactored with spaces before `=` and after and in other places -> like in the middle of print etc - in the manner of p3 standards. PyCharm should tell you where correction should be done. 

@hezyrof1997 Can you take that? We need it for next release.

### Example

![image](https://user-images.githubusercontent.com/56960469/115273907-6afee280-a140-11eb-8ae3-21768a3975ed.png)

**Comment by hezyrof1997** [comment]
Sure thing, im on it!

**Comment by kpiechura** [comment]
ok, good. Closing
